import type { NextPage } from "next";
import Head from "next/head";

import { About, BackgroundCircles, Contact, Experience, Header, Hero, Projects, Skills } from "../src/components/";

const Home: NextPage = () => (
  <div className="bg-[#202020] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 customScrollbar">
    <Head>
      <title>Emji&apos;s Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <BackgroundCircles />
    <section id="hero" className="snap-start">
      <Hero />
    </section>
    <section id="about" className="snap-center">
      <About />
    </section>
    <section id="experience" className="snap-start">
      <Experience />
    </section>
    <section id="skills" className="snap-center">
      <Skills />
    </section>
    <section id="projects" className="snap-end">
      <Projects />
    </section>
    <section id="contact" className="snap-center">
      <Contact />
    </section>
  </div>
);

export default Home;
