import type { NextPage } from "next";
import Head from "next/head";

import { Header } from "../src/components/";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Emji&apos;s Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
  </div>
);

export default Home;
